name: "First workflow file"
on:
  workflow_dispatch:
    inputs:
      deployEnv:
        description: "Specify which environment to use"
        required: true
        type: environment
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: |
          pwd
      - name: list items
        run: |
          ls -lart
      - name: Build docker
        run: |
          docker build -f src/Dockerfile -t calculator:1.0