name: "First workflow file"
on:
  workflow_dispatch:
    inputs:
      deployEnv:
        description: "Specify which environment to use"
        required: true
        type: environment
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version
        run: |
          node --version
      - name: Build docker
        run: |
          docker build -t calculator:1.0 ./src